--- !ditz.rubyforge.org,2008-03-06/project 
name: ndb
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: ndb
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.1.2
  status: :released
  release_time: 2010-04-27 07:53:09.817074 Z
  log_events: 
  - - 2010-04-14 06:40:27.435513 Z
    - Scott Taylor <scott@railsnewbie.com>
    - created
    - ""
  - - 2010-04-27 07:53:09.817084 Z
    - Scott Taylor <scott@railsnewbie.com>
    - released
    - Compatiblity with node v0.1.91
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.1.3
  status: :released
  release_time: 2010-05-14 06:58:06.417526 Z
  log_events: 
  - - 2010-05-14 06:53:24.116180 Z
    - Scott Taylor <scott@railsnewbie.com>
    - created
    - ""
  - - 2010-05-14 06:58:06.417539 Z
    - Scott Taylor <scott@railsnewbie.com>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.1.4
  status: :released
  release_time: 2010-05-20 05:40:28.490184 Z
  log_events: 
  - - 2010-05-16 22:49:19.982336 Z
    - Scott Taylor <scott@railsnewbie.com>
    - created
    - ""
  - - 2010-05-20 05:40:28.490194 Z
    - Scott Taylor <scott@railsnewbie.com>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.1.5
  status: :released
  release_time: 2010-05-30 06:09:35.735608 Z
  log_events: 
  - - 2010-05-21 05:52:57.654953 Z
    - Scott Taylor <scott@railsnewbie.com>
    - created
    - ""
  - - 2010-05-30 06:09:35.735622 Z
    - Scott Taylor <scott@railsnewbie.com>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.2.0
  status: :released
  release_time: 2010-08-20 20:49:15.490929 Z
  log_events: 
  - - 2010-08-20 20:41:15.642505 Z
    - Scott Taylor <scott@railsnewbie.com>
    - created
    - ""
  - - 2010-08-20 20:49:15.490944 Z
    - Scott Taylor <scott@railsnewbie.com>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.2.1
  status: :released
  release_time: 2010-11-02 07:11:07.604460 Z
  log_events: 
  - - 2010-11-02 07:10:42.277425 Z
    - Scott Taylor <scott@railsnewbie.com>
    - created
    - Add node 0.3.0 support
  - - 2010-11-02 07:11:07.604473 Z
    - Scott Taylor <scott@railsnewbie.com>
    - released
    - ""
